[build]
  context = "production"
  publish = "public"
  command = "hugo"
  functions = "netlify/functions"
  
[context.production.environment]
  HUGO_ENV = "production"
  HUGO_BASEURL = "https://www.windandbones.com"


[build.environment]
  HUGO_VERSION = "0.115.1"

[functions]
  node_bundler = "esbuild"