[build]
  command = "hugo --gc --minify --buildFuture -b $URL"
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  HUGO_VERSION = "0.134.2"
  HUGO_ENV = "production"  # Optional but recommended for production builds

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/404/"
  status = 404