[build]
  command = "npm install && hugo --minify"
  publish = "public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[build.environment]
  HUGO_VERSION = "0.115.1"

[functions]
  node_bundler = "esbuild"