[build]
  command = "npm install && hugo --minify"
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  HUGO_VERSION = "0.98.0"


[functions]
  node_bundler = "esbuild"

[[redirects]]
	from = "/*"
	to = "/404/"
	status = 404